config/routes.rb
Rails.application.routes.draw do
  # just add this code for all of the below
  # makes the 7 crud routes
  root to: 'restaurants#index'
  resources :restaurants

  # lets say you want to limit what they do, so youd don't get all seven
  # resources :restaurants, only: [:index, :show]
  # resources :restaurants, except: [:destroy, :update, :new, :create, :edit] # same as above


  # # routes for restrauants crud CRUD! (see letters below)
  # # VERB 'PATH', to: 'CONTROLLER_PREFIX#ACTION'

  # # create a new restrant (C)
  # # 2 routes, one to show the form one to create the restauant
  # # show the form
  # get 'restaurants/new', to: 'restaurants#new' # form page
  # # posts to one of the paths below, if you have a different verb you can use the same location
  # post 'restaurants', to: 'restaurants#create' # creates new rest

  # # list all restrauanrts (R)
  # get 'restaurants', to: 'restaurants#index'

  # # show a speicifc restarant (R)
  # get 'restaurans/:id', to: 'restaurants#show' #note how even if url is single, method is on plural

  # # update a secific restrant (U)
  # # get 'restaurants/update', to: << not this, need to know WHICH one you will change
  # # edit is a better word than update
  # get 'restaurants/:id/edit', to: 'restaurants#edit' # form page
  # patch 'restaurants/:id', to: 'restaurants#update'

  # # delete a specific restranut (D)
  # delete 'restaurants/:id', to: 'restaurants#destroy'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :destroy, :update]

  def index
      # @restaurants = Restaurant.all
    # now goes to the view before moving onto other methods
    # want to show latest first so change to
    @restaurants = Restaurant.all.order(created_at: :desc)
  end

  def show
    # @restaurant = Restaurant.find(?)
    # has dynamic variable, so need to find with params
        # @restaurant = Restaurant.find(params[:id]) see before_action
    # params[:id] is a string, but this is so common active record handles this for you
  end

  def new
    # new create edit update are all very similar
    # new has form
    @restaurant = Restaurant.new
  end

  def create
    # Restaurant.create(name: params[:name], address: params[:address],...)
    # if you had 20 fields you have to do this all over again...
    #   so instead you do this:
    # <form action="/restaurants" method="post">
    #   <!-- the above is found from looking at the routes page -->
    #   <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    #   <input type="text" name="restaurant[name]" />
    #   <input type="text" name="restaurant[address]" />
    #   <input type="number" name="restaurant[rating]" />
    #   <input type="submit" />
    # </form>
    # difference is, when you submit, all of the attributes are inside a restaurant hash
    # so can do this:
          # Restaurant.create(params[:restaurant])
    # but you cannot do this... in rails
    # lets say you have a feild, which is true or false
    # published starts as fale, and can be set to true by admin
    # final users can only see restaurants which were published
    # could go to this form in the app... if I was a hacker...
    # inspect, and add a new field, like name="restaurant[publsiehd]" value="true",
    # then you are submitting...
    # now you've been hacked!
    # so you need to do something else... whitelist what has been accepted
    # create private method
    Restaurant.create(restaurant_params)
    # don't need to send params as they are more global... or something

    redirect_to restaurants_path
    # this now allows feedback...
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    # .update is an instance method, which updates and saves - you are not calling the method on its own method

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  # strong parameters
  # whitelist what you acccept
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
    # now when I submit it works,
    #  but I don't get any feedback
    #  so check rails server
    # No template found for RestaurantsController#create, rendering head :no_content
    # Completed 204 No Content in 39ms (ActiveRecord: 3.2ms)
    # so path does not go anywhere yet
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    # but don't need to do this...
    # rails has
      #  before_action :set_restaurant
    # but index doesn't need it
    # so have only and execpt options
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :rating %>
  <%= f.number_field :rating, class: 'form-control' %>
  </div>


  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

<p></p>
<p>old form done manually</p>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>list of rs</h1>

<%= link_to 'Create new', new_restaurant_path %>

<table class="table">
  <tr>
    <th>name</th>
    <th>link 1</th>
    <th>link 2</th>
    <th>address</th>
    <th>rating</th>
    <th>delete</th>
  </tr>

  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant[:name] %></td>
      <td><%= link_to restaurant[:name], restaurant_path(restaurant) %></td>
      <td><%= link_to restaurant[:name], restaurant %></td>
      <td><%= restaurant[:address] %></td>
      <td><%= restaurant[:rating] %></td>
      <td><%= link_to '🥾', restaurant_path(restaurant), method: :delete %></td>
      <!-- no path to restaurant, same path... just different verb, same for patch, put (same), delete -->
      <!-- restaurant_path(restaurant), but default is get reequest, so just go to the page -->
      <!-- so need to say  method: :delete -->
    </tr>
  <% end %>

</table>

app/views/restaurants/new.html.erb
<%= render 'form' %>

<form action="/restaurants" method="post">
  <!-- the above is found from looking at the routes page -->
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="restaurant[name]" />
  <input type="text" name="restaurant[address]" />
  <input type="number" name="restaurant[rating]" />
  <input type="submit" />
</form>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %>
  <%= '*' * @restaurant.rating %>
</h1>

<p><%= @restaurant.address %></p>
<p><%= @restaurant.rating %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<br>
<%= link_to 'Go back to index', restaurants_path %>
<!-- bad to use the root_path, because if you want to change the root for a promation or whatever -->
<!-- then you will not have to refactor -->
<!-- good to have your root page as another page too -->